name: ci

on: [push]

jobs:
  tests:
    name: Tests with Huff Neo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install Huff
        uses: cakevm/huff-neo-toolchain@v1
        with:
          version: latest
      - name: Huff Tests
        uses: ./ # uses the action in the current repository
        with:
          with-location: "tests" # defaults to "src"
          with-extension: "*.t.huff" # default
          with-format: "table" # default, either ["list", "table", "json"]
